### ISSUE TITLE
Update qpid_proton to 0.18.1

### ISSUE THREAD

**Issue by gberginc** [ManageIQ/manageiq-providers-nuage#42]
Now that 0.18.1 has been released we should update it because its Ruby gem version removed the unnecessary `json` dependency.

https://github.com/ManageIQ/manageiq-providers-nuage/blob/377e47fe0fc2202e859a0e35304c06632a9cbf4c/bin/qpid_install.sh#L10

When testing the new version locally, please update the [`Gemfile`](https://github.com/ManageIQ/manageiq/blob/f6f7120749d16fd7825f83001dfd875cdecb903c/Gemfile#L119) by replacing the version to `~>0.18.1` and remove the reference to the git. Make sure the gem no longer causes conflicts with the rest of gems.

@miq-bot assign @gasper-vrhovsek 
/cc @gasper-vrhovsek as I am not sure if I can assign to you

**Comment by chargio** [comment]
@gberginc It seems that you assigned it to the wrong alias

**Comment by gberginc** [comment]
@chargio Problem is that our team can not be assigned to. I remember having the same problem before, so I cced @gasper-vrhovsek to make sure he sees that.

I asked @bronaghs yesterday if there is anything we can do. for PRs I don't have such a big problem, but for issues I would rather see if we are able to assigned them so that people are aware that these issues will be handled by our team.

**Comment by gasper-vrhovsek** [comment]
@gberginc noted.

**Comment by gberginc** [comment]
@miq-bot assign gberginc

**Comment by gberginc** [comment]
Both PRs merged.
