### ISSUE TITLE
Long delays processing Nuage events

### ISSUE THREAD

**Issue by gberginc** [ManageIQ/manageiq-providers-nuage#47]
We are experiencing long delays when listening for Nuage events in this provider. What's worse is that delays are increasing over time. Check this dump from the database (query used was `select id, event_type, timestamp, created_on, EXTRACT(EPOCH FROM (created_on - timestamp)) from event_streams where source = 'NUAGE' order by id desc`):

<img width="770" alt="screen shot 2017-11-29 at 08 01 50" src="https://user-images.githubusercontent.com/1437960/33366900-fc83f106-d4ec-11e7-85b0-3ce87b2c1b9e.png">

Top rows indicate 10 minute delays.

Adding `sleep_poll_normal` after [this line](https://github.com/ManageIQ/manageiq-providers-nuage/blob/master/app/models/manageiq/providers/nuage/network_manager/event_catcher/runner.rb#L19) reduces this dramatically:
<img width="760" alt="screen shot 2017-11-29 at 08 01 34" src="https://user-images.githubusercontent.com/1437960/33366996-468d8fe6-d4ed-11e7-8d8b-ed527d89813f.png">

Some events still take 20 or 30 seconds (something we need to investigate further), but in general this looks much better.

@bronaghs @Ladas @agrare @Fryguy Is there any other way of overcoming these issues? We based this event catcher on [Amazon](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/app/models/manageiq/providers/amazon/cloud_manager/event_catcher/runner.rb#L12), which also does not use `sleep_poll_normal`, but I don't know the details of the stream implementation which could be the main difference.

@miq-bot assign @gberginc
/cc @miha-plesko, @gasper-vrhovsek

**Comment by gberginc** [comment]
After a [comment](https://github.com/ManageIQ/manageiq-providers-nuage/pull/41#issuecomment-347804909) made by @Ladas about the green threads and after a discussion with @justinc1 and @miha-plesko, the problem could be related to the fact that qpid gem is only a binding for a system package which means that the "wait for IO" does not occur directly in Ruby, so perhaps context switches are not handled properly.

@justinc1 Was this my correct interpretation?

**Comment by Ladas** [comment]
@gberginc from my personal experience, e.g. doing lots and lots of very quick DB queries never switches context. So the sleep_poll_normal is the way to make sure the context is switched.

**Comment by justinc1** [comment]
> that the "wait for IO" does not occur directly in Ruby, so perhaps context switches are not handled properly

If I understand correctly, a C library for qpid is called under the hood. The rest of possible explanation is more about what would that mean in python green threads. If I call python network_socket.read(), then (after being monkey patched by greenthreads), that either:
- reads data if data available
- or executes some other python greenthread
But if I directly use read() from libc (assuming I look into internals of python socket class to get file descriptor), then greenthread code cannot intercept my call to libc read(). If socket is nonblocking, code might just spin in loop waiting for data.

Disclaimer: I didn't try to run any ruby code under gdb or strace to verify this. It is just a long shot.

**Comment by miha-plesko** [comment]
I think explanation that @justinc1 provides seems quite possible. Also, there seems to only exist such problem with nuage provider that uses system-dependent library (qpid_proton gem depends on qpid system library), but not with others, like openstack with pure-ruby gem "fog".

**Comment by miha-plesko** [comment]
I have some great news! Shifting to qpid_proton version 0.19.0 (ws 0.18.1 until now) resolved this issue!

I've hit Nuage with 12 events / sec and the response time was constant:

![capture](https://user-images.githubusercontent.com/8102426/34818457-1ee08bb6-f6bb-11e7-9bdc-c66b45278286.PNG)

This is the PR that shifts qpid_proton version: https://github.com/ManageIQ/manageiq-providers-nuage/pull/58
