### ISSUE TITLE
Validation of AMQP endpoints goes into a loop if wrong password is provided

### ISSUE THREAD

**Issue by gasper-vrhovsek** [ManageIQ/manageiq-providers-nuage#50]
I have just tested this now. With correct credentials the validation succedes in less than a second, but if i provide a wrong username the connection gets stuck in a loop and the validation never ends.

/cc @gberginc @miha-plesko

**Comment by gasper-vrhovsek** [comment]
I manage to reproduce this every time i enter an '@' in the password input field. Other wrong passwords fail as expected. But using '@' triggers the infinite loop. This needs further investigation.

**Comment by gasper-vrhovsek** [comment]
When an '@' is present in the password something like this gets generated as the url for amqp:
`username:pass@word@vsd01.phd.plm.nuagedemo.net:5672` which fails (I suspect qpid is splitting credentials and endpoint at the '@' char). Solution would be url encoding both username and password, since until now we always used already encoded usernames and passwords in the UI form.

**Comment by juliancheal** [comment]
This PR fixes this problem doesn't it? https://github.com/ManageIQ/manageiq-providers-nuage/pull/51 So we can close this Issue? /cc @gasper-vrhovsek

**Comment by gasper-vrhovsek** [comment]
Yes, @juliancheal , closing.
